---
title: "Animation Notebook"
author: Randy Yee
output: revealjs::revealjs_presentation
---

```{r, echo=FALSE}
options(scipen=10000)

library(tidyverse)
library(ggplot2)
library(gganimate)
library(extrafont)
library(scales)
```

```{r, echo=FALSE}
df <- read_delim(file.choose(), 
                   "\t", 
                   escape_double = FALSE,
                   trim_ws = TRUE,
                   col_types = cols(.default = col_character(), 
                                    targets = col_double(),
                                    qtr1 = col_double(),
                                    qtr2 = col_double(),
                                    qtr3 = col_double(),
                                    qtr4 = col_double(),
                                    cumulative = col_double()
                                    ) 
                   ) %>%
  pivot_longer(targets:cumulative,
               names_to = "attribute",
               values_to = "value") %>%
  unite("period", 
        c("fiscal_year", "attribute"),
        sep = "_", 
        remove = F)
```

# Clinical Performance Monitoring

## TOTAL: Clinical Cascade Indicators

```{r}
cc <- df %>%
  filter(indicator %in% c("HTS_TST", "HTS_TST_POS", "TX_CURR", "TX_NEW", "TX_PVLS") & 
           standardizeddisaggregate %in% c("Total Numerator", "Total Denominator")) %>%
  filter(attribute %in% c("targets", "cumulative"))%>%
  unite("labels", indicator, numeratordenom) %>%
  group_by(labels, fiscal_year, attribute) %>%
  summarise(value = sum(value, na.rm = T)) %>%
  ungroup() %>%
  pivot_wider(names_from = attribute, values_from = value) %>%
  mutate(Achievement = cumulative/targets) %>%
  rename(Cumulative = cumulative, Target = targets, `Fiscal Year` = fiscal_year, Indicator = labels) %>%
  pivot_longer(c("Cumulative", "Target", "Achievement"), names_to = "Type")
```

```{r}
ggplot(cc) +
  geom_col(aes(x = Cumulative, y = Indicator)) +
  geom_vline(aes(xintercept = Target)) +
  theme_minimal() +
  theme(panel.grid.major.y = element_blank()) +
  facet_wrap(~Indicator, scales = "free_y", ncol = 1) +
  transition_states(`Fiscal Year`,
                    transition_length = 3,
                    state_length = 20)

cca <- ggplot(data = cc, aes(x = Type, y = value, fill = factor(Indicator))) +
  geom_bar(stat = "identity") +
  transition_states(`Fiscal Year`,
                    transition_length = 3,
                    state_length = 20) +
  theme_minimal() +
  theme(text = element_text(family = "Gill Sans MT", size = 15),
        legend.position = "none",
        axis.title = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        #panel.grid = element_blank(),
        axis.line = element_line(size = 0.5, colour = "black"),
        axis.ticks = element_line(size = 0.5, colour = "black")
        ) +
  geom_text(aes(label = paste0(format(round(value/ 1e6, 1), trim = T), "m")), position = position_dodge(0.9), vjust = -1) +
  labs(title = "CLINICAL CASCADE RESULTS \nYear: {closest_state}") +
  scale_y_continuous(label = function(n){paste0(format(round(n/ 1e6, 1), trim = T), "m")})

cca <- animate(cc, height = 834, width = 1600)
cca
#anim_save("anim_cc1a.gif", cca)
```


## OU: Clinical Cascade Indicators

```{r}
df_cc2 <- df %>%
  filter(indicator %in% c("HTS_TST", "HTS_TST_POS", "TX_CURR", "TX_NEW", "TX_NET_NEW", "TX_PVLS") & standardizeddisaggregate %in% c("Total Numerator", "Total Denominator")) %>%
  filter(str_detect(period, "cumulative"))%>%
  unite("ind", indicator, numeratordenom) %>%
  group_by(operatingunit, ind, period) %>%
  summarise(value = sum(value, na.rm = T)) %>%
  ungroup()

df_cc2$period <- factor(df_cc2$period, levels = c("2018_cumulative", "2019_cumulative", "2020_cumulative"))

df_cc2$period <- str_replace(df_cc2$period, "_", " ")
df_cc2$period <- str_to_title(df_cc2$period)
```

```{r}
cc2 <- ggplot(data = df_cc2, aes(x = ind, y = value, fill = factor(ind))) +
  geom_bar(stat = "identity") +
  facet_wrap(~operatingunit) +
  transition_states(period,
                    transition_length = 3,
                    state_length = 20) +
  theme_minimal() +
  theme(text = element_text(family = "Gill Sans MT", size = 15),
        legend.position = "none",
        axis.title = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        #panel.grid = element_blank(),
        panel.border = element_rect(fill = NA, color = "grey")
        ) +
  labs(title = "CLINICAL CASCADE RESULTS \nYear: {closest_state}") +
  scale_y_continuous(label = function(n){paste0(format(round(n/ 1e6, 1), trim = T), "m")})

cc2a <- animate(cc2, height = 834, width = 1600)
anim_save("anim_cc2a.gif", cc2a)
```


## TOTAL: Age-Sex Pyramids RETIRED

```{r}
# df_HTS <- df %>%
#   filter(indicator == "HTS_TST" & standardizeddisaggregate == "Modality/Age/Sex/Result") %>%
#   filter(str_detect(period, "qtr")) %>%
#   group_by(trendsfine, sex, period) %>%
#   summarise(value = sum(value, na.rm = T)) %>%
#   ungroup() %>%
#   filter(!trendsfine %in% c("Unknown Age", "Retired Age Band", "Newer Age Band"))
# 
# df_HTS$period <- factor(df_HTS$period, levels = c("2018_qtr1", "2018_qtr2", "2018_qtr3", "2018_qtr4",
#                                                         "2019_qtr1", "2019_qtr2", "2019_qtr3", "2019_qtr4",
#                                                         "2020_qtr1", "2020_qtr2", "2020_qtr3", "2020_qtr4"))
# 
# df_HTS$period <- str_replace(df_HTS$period, "_", " ")
# df_HTS$period <- str_to_title(df_HTS$period)
```

```{r}
# agesex_pyr <- ggplot(data = df_HTS, aes(x = trendsfine, 
#                                            y = value, 
#                                            fill = sex)) +
#   geom_bar(data = subset(df_HTS, sex == "Female"), stat = "identity", aes(y = value *-1)) +
#   geom_bar(data = subset(df_HTS, sex == "Male"), stat = "identity") +
#   scale_y_continuous(breaks = seq(-2000000,1000000,1000000),
#                       labels = paste0(as.character(c(seq(2,0,-1), seq(1,1,1))),"m")) +
#   coord_flip() +
#   theme_minimal() +
#   theme(text = element_text(family = "Gill Sans MT"),
#         legend.position = "top",
#         legend.title = element_blank(),
#         axis.title = element_blank(),
#         #panel.grid = element_blank(),
#         axis.line = element_line(size = 0.5, colour = "black"),
#         axis.ticks = element_line(size = 0.5, colour = "black")
#         ) +
#   labs(title = "Total Number of Individuals Who Received HIV Testing Services and Test Results \nYear: {closest_state}") +
#   transition_states(period,
#                     transition_length = 3,
#                     state_length = 20)
# 
# as <- animate(agesex_pyr, height = 834, width = 1600)
# anim_save("anim_hts1a.gif", as)
```


## OU: Age-Sex Pyramids RETIRED

```{r, echo=FALSE}
# df_ou_HTS <- df %>%
#   filter(indicator == "HTS_TST" & standardizeddisaggregate == "Modality/Age/Sex/Result") %>%
#   filter(str_detect(period, "qtr")) %>%
#   group_by(operatingunit, trendsfine, sex, period) %>%
#   summarise(value = sum(value, na.rm = T)) %>%
#   ungroup() %>%
#   filter(!trendsfine %in% c("Unknown Age", "Retired Age Band", "Newer Age Band"))
# 
# df_ou_HTS$period <- factor(df_ou_HTS$period, levels = c("2018_qtr1", "2018_qtr2", "2018_qtr3", "2018_qtr4",
#                                                         "2019_qtr1", "2019_qtr2", "2019_qtr3", "2019_qtr4",
#                                                         "2020_qtr1", "2020_qtr2", "2020_qtr3", "2020_qtr4"))
# 
# df_ou_HTS$period <- str_replace(df_ou_HTS$period, "_", " ")
# df_ou_HTS$period <- str_to_title(df_ou_HTS$period)
```

```{r}
# agesex_pyr1 <- ggplot(data = df_ou_HTS, aes(x = trendsfine, 
#                                            y = value, 
#                                            fill = sex)) +
#   geom_bar(data = subset(df_ou_HTS, sex == "Female"), stat = "identity", aes(y = value *-1)) +
#   geom_bar(data = subset(df_ou_HTS, sex == "Male"), stat = "identity") +
#   coord_flip() +
#   facet_wrap(~operatingunit) +
#   theme_minimal() +
#   theme(text = element_text(family = "Gill Sans MT"),
#         legend.position = "top",
#         legend.title = element_blank(),
#         axis.title = element_blank()
#         )+
#   labs(title = "Total Number of Individuals Who Received HIV Testing Services and Test Results \nYear: {closest_state} ")+
#   scale_y_continuous(breaks = seq(-600000,400000,100000),
#                      labels = paste0(as.character(c(seq(0.6,0,-0.1), seq(0.1,0.4,0.1))),"m")) +
#   transition_states(period,
#                     transition_length = 3,
#                     state_length = 20)
# 
# #anim_agesex_pyr1
# as1 <- animate(agesex_pyr1, height = 834, width = 1600)
# as1
# anim_save("anim_hts2.gif", as1)
```

## TOTAL: HTS Age-Sex Pyramids

```{r}
df_htsind1 <- df %>%
  filter(indicator =="HTS_TST" & standardizeddisaggregate == "Modality/Age/Sex/Result") %>%
  filter(str_detect(period, "qtr")) %>%
  group_by(indicator, statushiv, trendsfine, sex, period) %>%
  summarise(value = sum(value, na.rm = T)) %>%
  ungroup() %>%
  filter(!trendsfine %in% c("Unknown Age", "Retired Age Band", "Newer Age Band"))

df_htsind1$period <- factor(df_htsind1$period, levels = c("2018_qtr1", "2018_qtr2", "2018_qtr3", "2018_qtr4",
                                                        "2019_qtr1", "2019_qtr2", "2019_qtr3", "2019_qtr4",
                                                        "2020_qtr1", "2020_qtr2", "2020_qtr3", "2020_qtr4"))

df_htsind1$period <- str_replace(df_htsind1$period, "_", " ")
df_htsind1$period <- str_to_title(df_htsind1$period)
```

```{r}
agesex_pyr_totall <- ggplot(data = df_htsind1, aes(x = trendsfine, 
                                           y = value, 
                                           fill = sex)) +
  geom_bar(data = subset(df_htsind1, sex == "Female"), aes(y = value *-1, fill = statushiv), stat = "identity") +
  geom_bar(data = subset(df_htsind1, sex == "Male"), aes(fill = statushiv), stat = "identity") +
  geom_hline(yintercept = 0) +
  coord_flip() +
  scale_y_continuous(breaks = seq(-3000000,1000000,500000),
                      labels = paste0(as.character(c(seq(3,0,-0.5), seq(0.5,1,0.5))),"m")) +
  theme_minimal() +
  theme(text = element_text(family = "Gill Sans MT", size = 15),
        legend.position = "top",
        legend.title = element_blank(),
        axis.title = element_blank(),
        #panel.grid = element_blank(),
        axis.line = element_line(size = 0.5, colour = "black"),
        axis.ticks = element_line(size = 0.5, colour = "black")
        # panel.border = element_rect(fill = NA, color = "grey"),
        # legend.justification = c(1,0), 
        # legend.position = c(1,0)
        ) +
  labs(title = "TOTAL NUMBER OF INDIVIDUALS TESTED WITH RESULTS \nYear: {closest_state} ", x = "Age", y = "Total") +
  transition_states(period,
                    transition_length = 3,
                    state_length = 20)

as2 <- animate(agesex_pyr_totall, height = 834, width = 1600)
anim_save("anim_hts1a.gif", as2)
```


## OU: HTS Age-Sex Pyramids

```{r}
df_htsind <- df %>%
  filter(indicator =="HTS_TST" & standardizeddisaggregate == "Modality/Age/Sex/Result") %>%
  filter(str_detect(period, "qtr")) %>%
  group_by(operatingunit, indicator, statushiv, trendsfine, sex, period) %>%
  summarise(value = sum(value, na.rm = T)) %>%
  ungroup() %>%
  filter(!trendsfine %in% c("Unknown Age", "Retired Age Band", "Newer Age Band"))

df_htsind$period <- factor(df_htsind$period, levels = c("2018_qtr1", "2018_qtr2", "2018_qtr3", "2018_qtr4",
                                                        "2019_qtr1", "2019_qtr2", "2019_qtr3", "2019_qtr4",
                                                        "2020_qtr1", "2020_qtr2", "2020_qtr3", "2020_qtr4"))

df_htsind$period <- str_replace(df_htsind$period, "_", " ")
df_htsind$period <- str_to_title(df_htsind$period)
```

```{r}
agesex_pyr_all <- ggplot(data = df_htsind, aes(x = trendsfine, 
                                           y = value, 
                                           fill = sex)) +
  geom_bar(data = subset(df_htsind, sex == "Female"), aes(y = value *-1, fill = statushiv), stat = "identity") +
  geom_bar(data = subset(df_htsind, sex == "Male"), aes(fill = statushiv), stat = "identity") +
  geom_hline(yintercept = 0) +
  coord_flip() +
  scale_y_continuous(breaks = seq(-600000,400000,100000),
                     labels = paste0(as.character(c(seq(0.6,0,-0.1), seq(0.1,0.4,0.1))),"m")) +
  facet_wrap(~operatingunit) +
  theme_minimal() +
  theme(text = element_text(family = "Gill Sans MT", size = 15),
        legend.position = "top",
        legend.title = element_blank(),
        axis.title = element_blank(),
        #panel.grid = element_blank(),
        panel.border = element_rect(fill = NA, color = "grey")#,
        # legend.justification = c(1,0), 
        # legend.position = c(1,0)
        ) +
  labs(title = "TOTAL NUMBER OF INDIVIDUALS TESTED WITH RESULTS \nYear: {closest_state} ", x = "Age", y = "Total") +
  transition_states(period,
                    transition_length = 3,
                    state_length = 20)

as3 <- animate(agesex_pyr_all, height = 834, width = 1600)
anim_save("anim_hts2a.gif", as3)

```

## Map

```{r}
library(leaflet)
library(rnaturalearth)
world <- worldw
```

## Sankey

```{r}
df_htssand <- df %>%
  filter(indicator == c("HTS_TST_POS") & standardizeddisaggregate == "Modality/Age/Sex/Result") %>%
  filter(str_detect(period, "qtr")) %>%
  group_by(indicator, modality, trendsfine, sex, period) %>%
  summarise(value = sum(value, na.rm = T)) %>%
  ungroup() %>%
  filter(!trendsfine %in% c("Unknown Age", "Retired Age Band", "Newer Age Band"))

df_htssand$period <- factor(df_htssand$period, levels = c("2018_qtr1", "2018_qtr2", "2018_qtr3", "2018_qtr4",
                                                        "2019_qtr1", "2019_qtr2", "2019_qtr3", "2019_qtr4",
                                                        "2020_qtr1", "2020_qtr2", "2020_qtr3", "2020_qtr4"))

df_htssand$period <- str_replace(df_htssand$period, "_", " ")
df_htssand$period <- str_to_title(df_htssand$period)
```

```{r}
#library(ggalluvial)
ggplot(df_htssand, aes(y = value, axis1 = modality, axis2 = sex, axis3 = trendsfine)) +
  geom_alluvium(aes(fill = indicator), width = 0, knot.pos = 0, reverse = F) +
  geom_stratum() +
  geom_text(stat = "stratum", infer.label = T) +
  scale_x_discrete(limits = c("Modality", "Sex", "Age")) +
  theme_minimal() +
  guides(fill = F) #+
  # coord_flip() +
  # transition_states(period,
  #                   transition_length = 3,
  #                   state_length = 20)
```

## TOTAL: Yield

```{r}
df_htsyield <- df %>%
  filter(indicator %in% c("HTS_TST", "HTS_TST_POS") & standardizeddisaggregate == "Modality/Age/Sex/Result") %>%
  filter(str_detect(period, "qtr")) %>%
  group_by(indicator, trendsfine, sex, period) %>%
  summarise(value = sum(value, na.rm = T)) %>%
  ungroup() %>%
  filter(!trendsfine %in% c("Unknown Age", "Retired Age Band", "Newer Age Band"))

df_htsyield$period <- factor(df_htsyield$period, levels = c("2018_qtr1", "2018_qtr2", "2018_qtr3", "2018_qtr4",
                                                        "2019_qtr1", "2019_qtr2", "2019_qtr3", "2019_qtr4",
                                                        "2020_qtr1", "2020_qtr2", "2020_qtr3", "2020_qtr4"))

df_htsyield$period <- str_replace(df_htsyield$period, "_", " ")
df_htsyield$period <- str_to_title(df_htsyield$period)

df_htsyield1 <- bind_rows(df_htsyield, df_htsyield %>%
          group_by(trendsfine, sex, period) %>%
          summarise(
                    value = value[indicator=="HTS_TST_POS"]/value[indicator=="HTS_TST"],
                    indicator = "Yield"
                    )%>%
            ungroup())
```

```{r}
yield_pyr <- ggplot(data = df_htsyield1, aes(x = trendsfine, 
                                           y = value, 
                                           fill = sex)) +
    geom_point(data = df_htsyield1 %>% filter(indicator == "Yield" & sex == "Female"), 
               aes(y = value *-1,fill = sex), 
               stat = "identity", 
               color = "#FFA600",
               size = 5) +
  geom_point(data = df_htsyield1 %>% filter(indicator == "Yield" & sex == "Male"), 
             stat = "identity", 
             color = "#FFA600", 
             size = 5) +
  geom_hline(yintercept = 0) +
  coord_flip() +
  scale_y_continuous(labels = scales::percent) +
  theme_minimal() +
  theme(text = element_text(family = "Gill Sans MT", size = 15),
        legend.position = "none",
        #legend.title = element_blank(),
        axis.title = element_blank(),
        axis.line = element_line(size = 0.5, colour = "black"),
        axis.ticks = element_line(size = 0.5, colour = "black")
        ) +
  labs(title = "TESTING YIELD \nYear: {closest_state} ", x = "Age", y = "Total") +
  transition_states(period,
                    transition_length = 3,
                    state_length = 20)

as3 <- animate(yield_pyr, height = 834, width = 1600)
anim_save("anim_hts3.gif", as3)
```

## OU: YIELD

```{r}
df_htsyield2 <- df %>%
  filter(indicator %in% c("HTS_TST", "HTS_TST_POS") & standardizeddisaggregate == "Modality/Age/Sex/Result") %>%
  filter(str_detect(period, "qtr")) %>%
  group_by(indicator, operatingunit, trendsfine, sex, period) %>%
  summarise(value = sum(value, na.rm = T)) %>%
  ungroup() %>%
  filter(!trendsfine %in% c("Unknown Age", "Retired Age Band", "Newer Age Band"))

df_htsyield2$period <- factor(df_htsyield2$period, levels = c("2018_qtr1", "2018_qtr2", "2018_qtr3", "2018_qtr4",
                                                        "2019_qtr1", "2019_qtr2", "2019_qtr3", "2019_qtr4",
                                                        "2020_qtr1", "2020_qtr2", "2020_qtr3", "2020_qtr4"))

df_htsyield2$period <- str_replace(df_htsyield2$period, "_", " ")
df_htsyield2$period <- str_to_title(df_htsyield2$period)

df_htsyield3 <- bind_rows(df_htsyield2, df_htsyield2 %>%
          group_by(operatingunit, trendsfine, sex, period) %>%
          summarise(
                    value = ifelse(value[indicator=="HTS_TST"] == 0 | is.na(value[indicator=="HTS_TST"]),NA,value[indicator=="HTS_TST_POS"]/value[indicator=="HTS_TST"]),
                    indicator = "Yield"
                    )%>%
            ungroup())
```

```{r}
yield_pyr1 <- ggplot(data = df_htsyield3, aes(x = trendsfine, 
                                           y = value, 
                                           fill = sex)) +
    geom_point(data = df_htsyield3 %>% filter(indicator == "Yield" & sex == "Female"), 
               aes(y = value *-1,fill = sex), 
               stat = "identity", 
               color = "#FFA600",
               size = 5) +
  geom_point(data = df_htsyield3 %>% filter(indicator == "Yield" & sex == "Male"), 
             stat = "identity", 
             color = "#FFA600", 
             size = 5) +
  geom_hline(yintercept = 0) +
  facet_wrap(~operatingunit) +
  coord_flip() +
  scale_y_continuous(labels = scales::percent) +
  theme_minimal() +
  theme(text = element_text(family = "Gill Sans MT", size = 15),
        legend.position = "none",
        #legend.title = element_blank(),
        axis.title = element_blank(),
        axis.line = element_line(size = 0.5, colour = "black"),
        axis.ticks = element_line(size = 0.5, colour = "black"),
        panel.border = element_rect(fill = NA, color = "grey")
        ) +
  labs(title = "TESTING YIELD \nYear: {closest_state} ", x = "Age", y = "Total") +
  transition_states(period,
                    transition_length = 3,
                    state_length = 20)

as4 <- animate(yield_pyr1, height = 834, width = 1600)
anim_save("anim_hts4.gif", as4)
```

## OU: VL Supression
```{r}
df_vlsup <- df %>%
  filter(indicator %in% c("TX_PVLS") & standardizeddisaggregate == "Age/Sex/Indication/HIVStatus") %>%
  filter(str_detect(period, "qtr")) %>%
  group_by(numeratordenom, operatingunit, trendsfine, sex, period) %>%
  summarise(value = sum(value, na.rm = T)) %>%
  ungroup() %>%
  filter(!trendsfine %in% c("Unknown Age", "Retired Age Band", "Newer Age Band"))

df_vlsup$period <- factor(df_vlsup$period, levels = c("2018_qtr1", "2018_qtr2", "2018_qtr3", "2018_qtr4",
                                                        "2019_qtr1", "2019_qtr2", "2019_qtr3", "2019_qtr4",
                                                        "2020_qtr1", "2020_qtr2", "2020_qtr3", "2020_qtr4"))

df_vlsup$period <- str_replace(df_vlsup$period, "_", " ")
df_vlsup$period <- str_to_title(df_vlsup$period)

df_vlsup1 <- bind_rows(df_vlsup, df_vlsup %>%
          group_by(operatingunit, trendsfine, sex, period) %>%
          summarise(
                    value = ifelse(value[numeratordenom=="D"] == 0 | is.na(value[numeratordenom=="D"]),NA,value[numeratordenom=="N"]/value[numeratordenom=="D"]),
                    numeratordenom = "T"
                    )%>%
            ungroup())
```

```{r}
vl_pyr <- ggplot(data = df_vlsup1, aes(x = trendsfine, 
                                           y = value, 
                                           fill = sex)) +
    geom_point(data = df_vlsup1 %>% filter(numeratordenom == "T" & sex == "Female"), 
               aes(y = value *-1,fill = sex), 
               stat = "identity", 
               color = "#FFA600",
               size = 5) +
  geom_point(data = df_vlsup1 %>% filter(numeratordenom == "T" & sex == "Male"), 
             stat = "identity", 
             color = "#FFA600", 
             size = 5) +
  geom_hline(yintercept = 0) +
  facet_wrap(~operatingunit) +
  coord_flip() +
  scale_y_continuous(
                     breaks = seq(-1,1,0.5), 
                     labels = paste0(as.character(c(seq(100,0,-50), seq(50,100,50))),"%")) +
  theme_minimal() +
  theme(text = element_text(family = "Gill Sans MT", size = 15),
        legend.position = "none",
        #legend.title = element_blank(),
        axis.title = element_blank(),
        axis.line = element_line(size = 0.5, colour = "black"),
        axis.ticks = element_line(size = 0.5, colour = "black"),
        panel.border = element_rect(fill = NA, color = "grey")
        ) +
  labs(title = "VIRAL LOAD SUPPRESSION \nYear: {closest_state} ", x = "Age", y = "Total") +
  transition_states(period,
                    transition_length = 60,
                    state_length = 60) +
  ease_aes("cubic-in-out")
vl_pyr
#as4 <- animate(vl_pyr, height = 834, width = 1600)
#anim_save("anim_vl1.gif", as4)
```

## SNU PRIORITY: Yield

```{r}
df_htsyield3 <- df %>%
  filter(indicator %in% c("HTS_TST", "HTS_TST_POS") & standardizeddisaggregate == "Modality/Age/Sex/Result") %>%
  filter(str_detect(period, "qtr")) %>%
  group_by(indicator, snuprioritization, trendsfine, sex, period) %>%
  summarise(value = sum(value, na.rm = T)) %>%
  ungroup() %>%
  filter(!trendsfine %in% c("Unknown Age", "Retired Age Band", "Newer Age Band"))

df_htsyield3$period <- factor(df_htsyield3$period, levels = c("2018_qtr1", "2018_qtr2", "2018_qtr3", "2018_qtr4",
                                                        "2019_qtr1", "2019_qtr2", "2019_qtr3", "2019_qtr4",
                                                        "2020_qtr1", "2020_qtr2", "2020_qtr3", "2020_qtr4"))

df_htsyield3$period <- str_replace(df_htsyield3$period, "_", " ")
df_htsyield3$period <- str_to_title(df_htsyield3$period)

df_htsyield3 <- bind_rows(df_htsyield3, df_htsyield3 %>%
          group_by(snuprioritization, trendsfine, sex, period) %>%
          summarise(
                    value = ifelse(value[indicator=="HTS_TST"] == 0 | is.na(value[indicator=="HTS_TST"]),NA,value[indicator=="HTS_TST_POS"]/value[indicator=="HTS_TST"]),
                    indicator = "Yield"
                    )%>%
            ungroup())
```


```{r}
yield_pyr2 <- ggplot(data = df_htsyield3, aes(x = trendsfine, 
                                           y = value, 
                                           fill = sex)) +
    geom_point(data = df_htsyield3 %>% filter(indicator == "Yield" & sex == "Female"), 
               aes(y = value *-1,fill = sex), 
               stat = "identity", 
               color = "#FFA600",
               size = 5) +
  geom_point(data = df_htsyield3 %>% filter(indicator == "Yield" & sex == "Male"), 
             stat = "identity", 
             color = "#FFA600", 
             size = 5) +
  geom_hline(yintercept = 0) +
  facet_wrap(~snuprioritization) +
  coord_flip() +
  scale_y_continuous(labels = scales::percent) +
  theme_minimal() +
  theme(text = element_text(family = "Gill Sans MT", size = 15),
        legend.position = "none",
        #legend.title = element_blank(),
        axis.title = element_blank(),
        axis.line = element_line(size = 0.5, colour = "black"),
        axis.ticks = element_line(size = 0.5, colour = "black"),
        panel.border = element_rect(fill = NA, color = "grey")
        ) +
  labs(title = "TESTING YIELD \nYear: {closest_state} ", x = "Age", y = "Total") +
  transition_states(period,
                    transition_length = 3,
                    state_length = 20)

as5 <- animate(yield_pyr2, height = 834, width = 1600)
anim_save("anim_hts5.gif", as5)
```

## SNU: Yield

```{r}
ou_list <- unique(df$operatingunit)

df_htsyield3 <- df %>%
  filter(indicator %in% c("HTS_TST", "HTS_TST_POS") & standardizeddisaggregate == "Modality/Age/Sex/Result") %>%
  filter(str_detect(period, "qtr")) %>%
  group_by(indicator, snuprioritization, trendsfine, sex, period) %>%
  summarise(value = sum(value, na.rm = T)) %>%
  ungroup() %>%
  filter(!trendsfine %in% c("Unknown Age", "Retired Age Band", "Newer Age Band"))

df_htsyield3$period <- factor(df_htsyield3$period, levels = c("2018_qtr1", "2018_qtr2", "2018_qtr3", "2018_qtr4",
                                                        "2019_qtr1", "2019_qtr2", "2019_qtr3", "2019_qtr4",
                                                        "2020_qtr1", "2020_qtr2", "2020_qtr3", "2020_qtr4"))

df_htsyield3$period <- str_replace(df_htsyield3$period, "_", " ")
df_htsyield3$period <- str_to_title(df_htsyield3$period)

df_htsyield3 <- bind_rows(df_htsyield3, df_htsyield3 %>%
          group_by(snuprioritization, trendsfine, sex, period) %>%
          summarise(
                    value = ifelse(value[indicator=="HTS_TST"] == 0 | is.na(value[indicator=="HTS_TST"]),NA,value[indicator=="HTS_TST_POS"]/value[indicator=="HTS_TST"]),
                    indicator = "Yield"
                    )%>%
            ungroup())
```
